apiVersion: v1
kind: ServiceAccount
metadata:
  name: devtool-sa-207-211-161-111
  namespace: devtool
  labels:
    app.kubernetes.io/name: devtool
    app.kubernetes.io/instance: devtool-207-211-161-111
    app.kubernetes.io/managed-by: agent
  annotations:
    # Ensures logs/auditing can trace workloads back to this SA
    iam.gke.io/gcp-service-account: "" # (only if using GKE + Workload Identity)
    eks.amazonaws.com/role-arn: ""    # (only if using EKS IRSA)
    # you can add audit annotations like:
    audit.openpolicyagent.org/trace: "true"
#automountServiceAccountToken: false  # 🔒 if set to true, prevents accidental token mounting unless needed
