apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default-sa-207-211-161-111
    namespace: default
roleRef:
  kind: Role
  name: default-full-role
  apiGroup: rbac.authorization.k8s.io
