apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podlauncher-binding
  namespace: podlauncher
subjects:
  - kind: ServiceAccount
    name: podlauncher-sa-207-211-161-111
    namespace: podlauncher
roleRef:
  kind: Role
  name: podlauncher-role
  apiGroup: rbac.authorization.k8s.io
