apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k3s-full-cluster-rolebinding
subjects:
  - kind: ServiceAccount
    name: cluster-sa-207-211-161-111
    namespace: default
roleRef:
  kind: ClusterRole
  name: k3s-full-cluster-role
  apiGroup: rbac.authorization.k8s.io
