apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k3s-full-cluster-role
rules:
  # Core resources (Pods, Services, Configs, Secrets, PVCs, PVs, etc.)
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - pods/status
      - services
      - configmaps
      - secrets
      - persistentvolumeclaims
      - persistentvolumes
      - endpoints
      - events
      - namespaces
      - replicationcontrollers
      - serviceaccounts
      - nodes
      - nodes/status
      - nodes/proxy
      - componentstatuses
    verbs: ["get", "list", "create", "delete", "watch", "update", "patch"]

  # Batch resources (Jobs, CronJobs)
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "create", "delete", "watch", "update", "patch"]

  # Apps resources (Deployments, ReplicaSets, StatefulSets, DaemonSets)
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
    verbs: ["get", "list", "create", "delete", "watch", "update", "patch"]

  # Networking resources (Ingress, NetworkPolicy, Services, IngressClasses)
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - networkpolicies
      - ingressclasses
    verbs: ["get", "list", "create", "delete", "watch", "update", "patch"]

  # Policy resources (PodDisruptionBudgets, PodSecurityPolicies)
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
      - podsecuritypolicies
    verbs: ["get", "list", "create", "delete", "watch", "update", "patch"]

  # Autoscaling resources (HPAs)
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "create", "delete", "watch", "update", "patch"]

  # RBAC resources (ClusterRoles, Roles, Bindings)
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs: ["get", "list", "create", "delete", "watch", "update", "patch"]

  # Admission and API extension resources (CRDs, Webhooks)
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs: ["get", "list", "create", "delete", "watch", "update", "patch"]

  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs: ["get", "list", "create", "delete", "watch", "update", "patch"]

  # Resource quotas & limits
  - apiGroups: [""]
    resources:
      - resourcequotas
      - limitranges
    verbs: ["get", "list", "create", "delete", "watch", "update", "patch"]

  # Coordination resources (Leases, used by controllers)
  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs: ["get", "list", "create", "delete", "watch", "update", "patch"]

  # Storage resources (StorageClasses, VolumeAttachments, CSINodes)
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
      - volumeattachments
      - csinodes
    verbs: ["get", "list", "create", "delete", "watch", "update", "patch"]
